"""empty message

Revision ID: 36746a07a9e0
Revises: 2b0bd8073c7d
Create Date: 2015-09-18 13:51:57.583682

"""

# revision identifiers, used by Alembic.
revision = '36746a07a9e0'
down_revision = '2b0bd8073c7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    ### end Alembic commands ###
