"""empty message

Revision ID: 5422e8cab342
Revises: 36746a07a9e0
Create Date: 2015-09-20 10:00:51.355643

"""

# revision identifiers, used by Alembic.
revision = '5422e8cab342'
down_revision = '36746a07a9e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    ### end Alembic commands ###
